#C:\Perl\site\lib\LWP\bin
use IO::Select;
use HTTP::Response;
use HTTP::Request::Common qw(GET);
use URI::URL;
use IO::Socket::INET;
use Term::ANSIColor qw(:constants);
use MIME::Base64;
use LWP;
use HTTP::Cookies;
use HTML::Entities;
use URI::Escape;
use Win32::Console::ANSI;
use Term::ANSIColor;
use LWP::UserAgent;
use HTTP::Request;
use HTTP::Request::Common qw(POST);
use LWP::UserAgent;
use HTTP::Request::Common;
use Term::ANSIColor;
use HTTP::Request::Common qw(GET);
$ag = LWP::UserAgent->new();
use MIME::Base64;
my $time    = localtime;

	    print color('reset');
	system ("title mandra crew pass-gen V0.1");
system(($^O eq 'MSWin32') ? 'cls' : 'clear');
	
	                                    ################################## START ##################################
										
										
print colored ("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",'black on_red'),"\n";
print colored ("                       [ c0d3d bY ManDra creW membere ]                        ",'white on_red'),"\n";
print colored ("                              [ el ZinDYanII-tN ]                              ",'white on_red'),"\n";
print colored ("                           [ jUsT version 0.1 baby ]                           ",'white on_red'),"\n";
print colored ("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",'black on_red'),"\n";										
print colored ("\n                     ___ ___ _____ _______ __          __                    ",'green on_black'),"\n";
print colored ("                    |   Y   | _   |   _   |  |--.-----|  |_                    ",'green on_black'),"\n";
print colored ("                    |.      |.|   |___|   |  _  |  _  |   _|                   ",'green on_black'),"\n";
print colored ("                    |. |_|  `-|.  |_(__   |_____|_____|____|                   ",'green on_black'),"\n";
print colored ("                    |:  |   | |:  |:  1   |  mandra crew                       ",'green on_black'),"\n";
print colored ("                    |::.|:. | |::.|::.. . |  pass-fucker                       ",'green on_black'),"\n";
print colored ("                    `--- ---' `---`-------'     v0.1                           ",'green on_black'),"\n\n";                            
print colored ("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",'black on_red'),"\n";
print colored ("                                  [ thnx f0r ]                                 ",'white on_red'),"\n";
print colored ("            [ Spawn_Z | The Poet of FallaGa  | pedro vortex | adminet ]        ",'white on_red'),"\n";
print colored ("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++",'black on_red'),"\n\n";
print colored ("                       Start At $time                                      ",'white on_black'),"\n";
print color("green"),"[+] Victim ID : ";
my $user = <STDIN>;
chomp $user;
open (TEXT, '>>user.txt');
        print TEXT "$user\n";
        close (TEXT);
print color("green"),"[+] VCTM name : ";
my $A = <STDIN>;
chomp $A;
open (TEXT, '>>victim_data/A.txt');
        print TEXT "$A\n";
        close (TEXT);
print color("green"),"[+] VCTM lastname : ";
my $B = <STDIN>;
chomp $B;
open (TEXT, '>>victim_data/B.txt');
        print TEXT "$B\n";
        close (TEXT);
print color("green"),"[+] VCTM Phone num : ";
my $C = <STDIN>;
chomp $C;
open (TEXT, '>>victim_data/C.txt');
        print TEXT "$C\n";
        close (TEXT);
print color("green"),"[+] VCTM friend name : ";
my $D = <STDIN>;
chomp $D;
open (TEXT, '>>victim_data/D.txt');
        print TEXT "$D\n";
        close (TEXT);
print color("green"),"[+] VCTM nick name : ";
my $E = <STDIN>;
chomp $E;
open (TEXT, '>>victim_data/E.txt');
        print TEXT "$E\n";
        close (TEXT);
print color("green"),"[+] VCTM Mather name : ";
my $F = <STDIN>;
chomp $F;
open (TEXT, '>>victim_data/F.txt');
        print TEXT "$F\n";
        close (TEXT);
		passampl();
$res="$A"."_data";
    if (-e $res)
    {
    }
    else
    {
        mkdir $res or die "WE CAN NOT CREATE THE BOARD OF DIRECTORS: $res";
    }
sub passampl(){
$pass=$A.$B;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$A.$C;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$A.$D;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$A.$E;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$A.$F;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$A.$A;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$B.$B;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$B.$A;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$B.$C;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$B.$D;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$B.$E;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$B.$F;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$C.$A;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$C.$B;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$C.$C;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$C.$D;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$C.$E;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$C.$F;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
				$pass=$D.$A;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$D.$B;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$D.$C;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$D.$D;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$D.$E;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$D.$F;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
		$pass=$E.$A;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
				$pass=$E.$B;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
				$pass=$E.$C;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
				$pass=$E.$D;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
				$pass=$E.$E;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
				$pass=$E.$F;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
				$pass=$F.$A;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
						$pass=$F.$B;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);				
		$pass=$F.$C;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
						$pass=$F.$D;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
						$pass=$F.$E;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
						$pass=$F.$F;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);
						$pass=$F.$A;
print color("red"), " [pass] > $pass\n";
print color ('reset');
        open (TEXT, ">>pass_list_of_$A.txt");
        print TEXT "$pass\n";
        close (TEXT);neexxt();}
		sub neexxt(){
		system("simpol.pl")
		}